services:
  fiap.api:
    image: fiap.api
    build:
      context: .
      dockerfile: src/FIAP.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - fiap.sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  fiap.sqlserver:
  #  image: mcr.microsoft.com/mssql/server:2022-latest  # Geral
    image:  mcr.microsoft.com/azure-sql-edge:latest    # Especifico para Mac chip M1 em diante
    container_name: fiap-sqlserver
    ports:
      - "1433:1433" # Porta padrão do SQL Server
    environment:
      SA_PASSWORD: "1q2w3e4r@#$" # Deixe essa senha igual à definida no appsettings
      ACCEPT_EULA: "Y" # Aceitação da licença obrigatória
      MSSQL_PID: "Developer" # "Express" Ou "Developer" para a versão gratuita sem chave