version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: fiap.contatos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fiap
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: fiap.contatos_api
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=fiap;User=root;Password=admin;
    ports:
      - "8080:8080"
    networks:
      - app_network
    command: [ "dotnet", "FIAP.Contatos.dll" ]
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: