version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fiap.sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1q2w3e4r@#$
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - app_network
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: fiap.rabbitmq
    ports:
      - "5672:5672" # Porta de comunicação com aplicações (AMQP)
      - "15672:15672" # Porta da interface de administração web
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - app_network

  persistencia-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-persistencia
    container_name: fiap.persistencia_api
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=fiap.sqlserver,1433;Database=Contato-FIAP;User ID=sa;Password=1q2w3e4r@#$;Trusted_Connection=False; TrustServerCertificate=True;
    ports:
      - "8080:8080"
    networks:
      - app_network
    command: [ "dotnet", "persistencia-api.dll" ]
    volumes:
      - persistencia_data:/app

  cadastro-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-persistencia
    container_name: fiap.cadastro_api
    depends_on:
      - persistencia-api
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - PersistenciaApiUrl=http://fiap.persistencia_api:8080
    ports:
      - "8082:8080"
    networks:
      - app_network
    command: [ "dotnet", "cadastro-api.dll" ]
    volumes:
      - cadastro_data:/app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  app_network:
    driver: bridge

volumes:
  sqlserver_data:
  persistencia_data:
  cadastro_data:
  grafana_data: