global:
  scrape_interval: 15s # Intervalo padrão de coleta de métricas

scrape_configs:
  - job_name: 'aspnetcore_app'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5083'] 