version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles: ["amd64", "arm64"]
    container_name: fiap.sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1q2w3e4r@#$
      - MSSQL_PID=Express
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "1q2w3e4r@#$", "-Q", "select 1", "-C"]
      interval: 30s
      timeout: 10s
      retries: 15
    ports:
      - "1433:1433"
    networks:
      - app_network
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: masstransit/rabbitmq
    profiles: ["amd64", "arm64"]
    container_name: fiap.rabbitmq
    ports:
      - "5672:5672" # Porta de comunicação com aplicações (AMQP)
      - "15672:15672" # Porta da interface de administração web
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    profiles: ["amd64", "arm64"]
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    profiles: ["amd64", "arm64"]
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  persistencia-api:
    build:
      context: ..
      dockerfile: docker/amd64/Dockerfile
      target: persistencia-api
    container_name: fiap.persistencia_api
    profiles: ["amd64"]
    depends_on:
      sqlserver:
       condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=fiap.sqlserver,1433;Database=Contato-FIAP;User ID=sa;Password=1q2w3e4r@#$;Trusted_Connection=False; TrustServerCertificate=True;
      - RabbitMq__Host=rabbitmq
      - RabbitMq__User=admin
      - RabbitMq__Pass=admin
      - RabbitMq__Port=5672
    ports:
      - "8080:8080"
    networks:
      - app_network
    restart: always
    volumes:
      - persistencia_data:/app

  cadastro-api:
    build:
      context: ..
      dockerfile: docker/amd64/Dockerfile
      target: cadastro-api
    container_name: fiap.cadastro_api
    profiles: ["amd64"]
    depends_on:
      - persistencia-api
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development 
      - PersistenciaApiUrl=http://fiap.persistencia_api:8080
    ports:
      - "8082:8080"
    networks:
      - app_network
    volumes:
      - cadastro_data:/app

  persistencia-api-arm64:
    build:
      context: ..
      dockerfile: docker/arm64/Dockerfile
      target: persistencia-api
    container_name: fiap.persistencia_api
    profiles: ["arm64"]
    depends_on:
      sqlserver:
       condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=fiap.sqlserver,1433;Database=Contato-FIAP;User ID=sa;Password=1q2w3e4r@#$;Trusted_Connection=False; TrustServerCertificate=True;
      - RabbitMq__Host=rabbitmq
      - RabbitMq__User=admin
      - RabbitMq__Pass=admin
      - RabbitMq__Port=5672
    ports:
      - "8080:8080"
    networks:
      - app_network
    restart: always
    volumes:
      - persistencia_data:/app

  cadastro-api-arm64:
    build:
      context: ..
      dockerfile: docker/arm64/Dockerfile
      target: cadastro-api
    container_name: fiap.cadastro_api
    profiles: ["arm64"]
    depends_on:
      - persistencia-api-arm64
      - rabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development 
      - PersistenciaApiUrl=http://fiap.persistencia_api:8080
    ports:
      - "8082:8080"
    networks:
      - app_network
    volumes:
      - cadastro_data:/app


networks:
  app_network:
    driver: bridge

volumes:
  sqlserver_data:
  grafana_data:
  persistencia_data:
  cadastro_data: